version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    environment:
      # More permissive auth for development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      # Expose to host for direct access
      - "5432:5432"

  hub:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      # Hot reload - mount source code
      - ./hub:/app/hub:ro
      - ./config:/app/config:ro
      # Exclude node_modules to prevent conflicts
      - /app/node_modules
    command: ["npx", "nodemon", "hub/server.js"]
    ports:
      # Expose to host
      - "3000:3000"
      # Debug port for Node.js inspector
      - "9229:9229"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      target: builder
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      # Hot reload - mount source code
      - ./dashboard/src:/app/src:ro
      - ./dashboard/public:/app/public:ro
      - ./dashboard/index.html:/app/index.html:ro
      - ./dashboard/vite.config.js:/app/vite.config.js:ro
      # Exclude node_modules
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "8080:5173"

  demo-text-to-hex:
    build:
      context: ./micro-apps/demo-text-to-hex
      dockerfile: Dockerfile
      target: builder
    environment:
      NODE_ENV: development
      HUB_URL: http://hub:3000
    volumes:
      # Hot reload - mount source code
      - ./micro-apps/demo-text-to-hex/src:/app/src:ro
      - ./micro-apps/demo-text-to-hex/*.yaml:/app/:ro
      # Exclude node_modules
      - /app/node_modules
    command: ["npx", "nodemon", "src/server.js"]
    ports:
      - "3002:3002"

  pgadmin:
    # Always include pgAdmin in dev
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"

# Development-specific volume for faster I/O on Windows
volumes:
  postgres_data:
    driver: local
